version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn run test

workflows:
  test:
    jobs:
      - build:
          context: npm-demo
