version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm publish

workflows:
  test:
    jobs:
      - build:
          context: npm-demo