version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

workflows:
  test-then-deploy:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
